### ISSUE TITLE
 storefront does not show the products added in CP admin 

### ISSUE THREAD

**Issue by Rahamathulla** [inspire-software/yes-cart#101]
**Describe the bug**

**To Reproduce**
1. Go to ' admin console'
2. Click on add products, brands, catalogue, product types and add data.
3. Goto "Sales channels" > yescart shop > Overview. correct the errors marked with red X.
4. I am able to correct all the X red marked ones but the below one not sure 
Search: include sub categories

5. after setting up all the above data still , the products are not appearing in the store front.

**Expected behavior**
Store front should display the products added.
**Screenshots**
Please find attached screenshots

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : edge

**Additional context**
Adding the downloaded data from the store, if any data setup is missing, please let me know.

**Comment by inspire-software** [comment]
Hi,

If you have gone through the basic setup as in this video you should have the shop fully setup https://www.youtube.com/watch?v=I7QZja62WWw&list=PLFXlcPhFRUJp2piKzcrCaG0By8-X3bdm_

There is also business user manual that explains what different screens in admin are for and explanation on the effect of the configurations you apply https://docs.inspire-software.com/docs/display/YD/For+Business+Users

On point 3 - Overview screen X's don't mean errors they just show which configurations are currently setup for the sales channel "Search: include sub categories - X" simply means don't search in subcategories when viewing top level category (i.e. the customer has to navigate down to the category to which the product is assigned to see it). It is best to set this to "true" in shop attributes, but it will depend on how you wish products to be displayed.

If you know that products are configured correctly, then check if there are any errors in Tomcat logs as it could be there is some issue with indexing. 

Regards,
YC team

**Comment by Rahamathulla** [comment]
Thanks for your response. Can you share the data that can be imported in CP admin module to set up the same store as https://demo.yes-cart.org/. I hope this is feasible to setup through CP > Operations > Import.

 Its fine if it has only limited products. Thanks in advance.

**Comment by inspire-software** [comment]
If you follow the video it is all described there.
