### ISSUE TITLE
Is flatly theme missing on your demo site?

### ISSUE THREAD

**Issue by topstarnetwork** [inspire-software/yes-cart#33]
Hello, Is flatly theme missing on your demo site?from https://bootswatch.com/flatly/
Did you add to yes cart all bootswatch themes?
Regards,

**Comment by inspire-software** [comment]
Hi,

List of all currently added themes to core code is here: http://www.inspire-software.com/confluence/display/YC3EN/Themes . It does not include flatly, however there is no reason why you cannot just add it in your project, it is very easy, you can watch this video: https://www.youtube.com/watch?v=GMQ4wBlAAqA to see how to add it.

Hope this helps,
YC team

**Comment by topstarnetwork** [comment]
very nice of you thanks!
