### ISSUE TITLE
any plan to update angular?  

### ISSUE THREAD

**Issue by chenshao0594** [inspire-software/yes-cart#41]
any plan to update angular?  
 thank you!

**Comment by iazarny** [comment]
Have you tried to use already configured AWS image for development ? 
Here step by step instructions - http://www.inspire-software.com/confluence/display/YC3J/Running+Yes-Cart+on+AWS

Thanks, Igor

**Comment by inspire-software** [comment]
Yes we plan to upgrade to Angular4 which will come in the 3.4.0 release.
Watch this task: http://www.inspire-software.com/jira/browse/YC-842

Regards,
YC team

**Comment by inspire-software** [comment]
YC-842 has been completed and verified. 
Please ensure a clean build procedure:
1. Delete node_modules
2. Delete dist
3. Run npm install

Regards,
YC team
