### ISSUE TITLE
Error compiling local on 748bc18b3c37e7561bfd8824af4518433ec9589a

### ISSUE THREAD

**Issue by sergey-soloviov** [inspire-software/yes-cart#42]
I am trying to compile locally on MacOS and I am getting error:
```
> yes-cart-jam@3.4.0 build.dev /Users/sergey/Projects/yes-cart/manager/jam-jsclient/src/main/typescript
> gulp build.dev --color --env-config dev

[14:19:05] Requiring external module ts-node/register

/Users/sergey/Projects/yes-cart/manager/jam-jsclient/src/main/typescript/node_modules/ts-node/dist/index.js:160
                    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
                    ^
TSError: ⨯ Unable to compile TypeScript
tools/utils/seed/clean.ts (23,45): Property 'yellow' does not exist on type 'typeof "/Users/sergey/Projects/yes-cart/manager/jam-jsclient/src/main/typescript/node_modules/cha...'. (2339)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yes-cart-jam@3.4.0 build.dev: `gulp build.dev --color --env-config dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yes-cart-jam@3.4.0 build.dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sergey/.npm/_logs/2017-12-01T11_19_07_170Z-debug.log
```

Could you please add tags with release versions.

**Comment by iazarny** [comment]
Hi Sergey.
Could you  please provide node and npm versions ? 
Just build from master, looks ok for me 

------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:01 min
[INFO] Finished at: 2017-12-01T12:39:12Z
[INFO] Final Memory: 90M/215M
[INFO] ------------------------------------------------------------------------
[ec2-user@ip-172-31-21-39 yes-cart]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
[ec2-user@ip-172-31-21-39 yes-cart]$ no
node     nohup    nologin
[ec2-user@ip-172-31-21-39 yes-cart]$ node --version
v8.4.0
[ec2-user@ip-172-31-21-39 yes-cart]$ npm --version
5.4.0

------
As some workaround try to run 
npm install in manager/jam-jsclient/src/main/typescript and rebuild one more time.

Thanks, Igor

**Comment by sergey-soloviov** [comment]
```
MacBook-Pro-Sergej:yes-cart sergey$ node --version
v8.9.1
MacBook-Pro-Sergej:yes-cart sergey$ npm --version
5.5.1
```

**Comment by inspire-software** [comment]
Hi Sergey, 

Angular builds are quite sensitive to nodes/npm versions.
You should be able to run JAM on nodejs v5.12.0 and npm3.
Since you are using Mac we recommend you use Mac "port". It allows to install different packages easily, so you can activate/deactivate different versions of node and npm.

Currently we have Angular2 but soon we will upgrade to Angular4, keep watching this http://www.inspire-software.com/jira/browse/YC-842

Regards,
YC team

**Comment by khangaikhuu** [comment]
Hi  YC team,
i have tried with older version of nodejs/npm.
nodejs = v5.12.0
npm = 3.10.10
i'm getting such error.
Can you help me to compile on local?
[?[90m07:23:49?[39m] Error on fetch for tslib.js at file:///C:/..../yes-cart-master/manager/jam-jsclient/src/main/typescript/node_modules/tslib.js
Loading /http
Loading dist\tmp\app\app.module.js
Loading dist\tmp\app\main.js
Error: ENOENT: no such file or directory, open 'C:.....\yes-cart-master\manager\jam-jsclient\src\main\typescript\node_modules\tslib.js'
at Error (native)

**Comment by sergey-soloviov** [comment]
I was unable to install nodejs 5.12.0. To build I installed on VirtualBox CentOS Linux with nodejs 6.12.0. But the build also failed. See attached log.
[npm-debug.log](https://github.com/inspire-software/yes-cart/files/1527511/npm-debug.log)

**Comment by iazarny** [comment]
Hi Sergey. 
1. We already have configured vagrant box. Please look at env/vagrant
2. In README.md look at build procedure. It is very important to rub build procedure first time with clean parameter. Example - 
mvn clean install -Pmysql -PpaymentAll -Pdev -DskipTests=true

**Comment by inspire-software** [comment]
Hi @khangaikhuu,

We were able to reproduce your problem on a Windows machine. Seems like tslib needs path mapping in **prod** configuration of the build as well to make it work for Win.

> [?[90m07:23:49?[39m] Error on fetch for tslib.js at file:///C:/..../yes-cart-master/manager/jam-jsclient/src/main/typescript/node_modules/tslib.js

Please update and try to re-build.

Ref: https://github.com/inspire-software/yes-cart/commit/7119764873e48d8a91e6e6dfc1c35d8901c6fd5a

Regards,
YC team

**Comment by sergey-soloviov** [comment]
Back to error on Mac. The issues is still reproduces. On Linux I also did not have fun.
I downloaded nodejs 5.12.0 and npm 3.8.6. And no success. See 
[npm-debug.log](https://github.com/inspire-software/yes-cart/files/1530455/npm-debug.log).

**Comment by inspire-software** [comment]
Hi @sergey-soloviov,

It is really strange issues that you are having as we have confirmation that build is working correctly on OSX, Ubuntu and Windows now.

Looking at your npm, the failure occurs on post install:

> 70 verbose stack Error: yes-cart-jam@3.4.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`

One of core team guys said this could be that it is because the build is not entirely clean.

Could you please do the following:

1. Make sure you do git pull to have latest master
2. Delete src/main/typescript/node_modules and src/main/typescript/dist completely
3. go to src/main/typescript and run: npm install
4. then if successful run: npm run build.dev (this should start app on port 5555)
5. check the app on URL provided and make sure that it shows menu (there will be an application error window but that is ok, since we do not have web services started)

Let us know how far you get with this.

Regards,
YC team

**Comment by inspire-software** [comment]
Hi @sergey-soloviov, is your build running successfully now? It looks like the issue has been resolved but we wanted to confirm with you as well.

**Comment by sergey-soloviov** [comment]
Hi,

Yes, I was able to compile. The steps I used are the following:
1. Remove the content of `manager/jam-jsclient/src/main/typescript/node_modules` and `manager/jam-jsclient/src/main/typescript/dist`. 
2. `cd manager/jam-jsclient/src/main/typescript`
3. `npm install`. npm is of version 3.8.6 (nodejs of version 5.12.0)
4. `npm run build.dev`. This command do not starts the console.
5. Go to root folder of he project.
6. `mvn clean install -Pderby -PpaymentAll -Pdev`

**Comment by inspire-software** [comment]
Hi @sergey-soloviov, 

Glad to hear that it is all working for you now.

Just for the benefit of general knowledge: step 6 (mvn clean install) does steps 3 and 4. step 3 npm install is run during clean phase and step 4 is run during process-resources phase.

Regards,
YC team

**Comment by sauliusano** [comment]
Hi, I have the same issue on yc-3.3.1-ga release. Maybe you could backport the fix from master to yc-3.3.0-bugfix branch?

My setup:
Windows 10,
node v5.12.0
npm  v3.8.6
yc 3.3.1-ga

Notes: I cleared typescript directory and executed `npm install` from it

>my-project\manager\jam-jsclient\src\main\typescript\node_modules\ts-node\dist\index.js:160
                    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
                    ^
 TSError: ⨯ Unable to compile TypeScript
tools\utils\seed\clean.ts (23,45): Property 'yellow' does not exist on type 'typeof "my-project/manager/jam-jsclient/src/main/typescript/node_modules/chalk/types/...'. (2339)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! yes-cart-jam@3.3.1 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yes-cart-jam@3.3.1 postinstall script 'gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yes-cart-jam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yes-cart-jam
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yes-cart-jam
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     my-project\manager\jam-jsclient\src\main\typescript\npm-debug.log

**Comment by inspire-software** [comment]
Hi,

The original problem was reported on master (which is 3.4.0-SNAPSHOT) which has AngularJS 4. 3.3.1 is on AngularJS 2, so your problem must be something different. What we noticed is that AngularJS dependencies are very sensitive to versions of supporting libraries and because on 3.3.1 some dependencies are allowed to be "x or above" it could be that some of these causing issues.

Try to assess the version differences in package.json and what dependencies you have in node_modules. Another thing to try is to change the package.json to use only the exact version specified (i.e. without ^/~ etc).

3.4.0 is not so far away from release, so another option would be to consider using the master, rather than 3.3.1.

Regards,
YC team

**Comment by sauliusano** [comment]
Upgrade to 3.4.0-SNAPSHOT solved AngularJS issue, thanks.
