### ISSUE TITLE
Confluence is not working.

### ISSUE THREAD

**Issue by sfister5** [inspire-software/yes-cart#43]
I would like the User Guide to setup my own demo on either a Debian machine or Windows 10 laptop.
The User guide link is not working on normal site and the Confluence system seems to be having some big issues.  The contact page seems to also be having issues.
Thanks,
Steve

**Comment by sfister5** [comment]
How can I get a full demo of the enterprise software features?

I want to see how the manager works on the full environment with multi 
tenancy.

**Comment by inspire-software** [comment]
Hi,

You do not need YCE for multitenancy demo - it is part of the core on YC. You can create multiple shops in JAM and then create managers (in the organisation section) that only have access to specific shops. Each shop must have its own domain name so for local installation/demo you can map domains to "localhost" in /etc/hosts file (C:\Windows\System32\drivers\etc\hosts on Windows). 

If you want to find out about the YCE features or request a demo please contact us via http://www.yes-cart.org/#contact (please use partnerships and new projects subject). We also have YCE demo store here http://edemo.yes-cart.org for quick glance. 

Regards,
YC team

**Comment by inspire-software** [comment]
You can join our google group so that representative of our team will see your email and contact you directly. https://groups.google.com/forum/#!forum/yescart---open-source-ecommerce-platform

**Comment by inspire-software** [comment]
Confluence documentation has been now fully migrated to xwiki and can be found here http://www.inspire-software.com/documentation/wiki/docyescart/
