### ISSUE TITLE
Build Failed for 3.5.0-ga

### ISSUE THREAD

**Issue by abdullahvhdl** [inspire-software/yes-cart#52]
i am using  "mvn clean install -Pmysql -PpaymentAll -PftEmbededLucene -Pdev -DskipTests=true"

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\Abed\devops\projects\commerce\yes-cart-yc-3.5.0-ga\core\src\main\java\org\yes\cart\service\locator\impl\JnpInstantiationStrategyImpl.java:[27,16] error: package javax.rmi does not exist
[ERROR] C:\Abed\devops\projects\commerce\yes-cart-yc-3.5.0-ga\core\src\main\java\org\yes\cart\service\locator\impl\JnpInstantiationStrategyImpl.java:[70,27] error: cannot find symbol
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Yes Cart 3.5.0:
[INFO]
[INFO] Yes Cart ........................................... SUCCESS [  3.308 s]
[INFO] Yes cart common API ................................ SUCCESS [  4.465 s]
[INFO] Yes cart payment API ............................... SUCCESS [  4.223 s]
[INFO] Yes cart domain API ................................ SUCCESS [  7.689 s]
[INFO] Yes cart search .................................... SUCCESS [  0.718 s]
[INFO] Yes cart search API ................................ SUCCESS [  3.338 s]
[INFO] Yes cart persistence ............................... SUCCESS [  6.575 s]
[INFO] Yes cart search: Lucene core ....................... SUCCESS [  4.109 s]
[INFO] Yes cart core service .............................. FAILURE [  5.510 s]
[INFO] Yes cart core modules .............................. SKIPPED
[INFO] Yes cart core: Jobs API ............................ SKIPPED
[INFO] Yes cart search: Lucene embeded provider ........... SKIPPED
[INFO] Yes cart search: disabled provider ................. SKIPPED
[INFO] Yes cart core: Http support ........................ SKIPPED
[INFO] Yes cart core: WS support .......................... SKIPPED
[INFO] Yes cart payment modules ........................... SKIPPED
[INFO] Yes cart payment: Basic payment module Courier, In Store and Pre paid offline (+Test and TestExt) SKIPPED
[INFO] Yes cart core: Default order state machine ......... SKIPPED
[INFO] Yes cart core: JGroups cluster support ............. SKIPPED
[INFO] Yes cart core: WebServices cluster support ......... SKIPPED
[INFO] Yes cart core: reports support ..................... SKIPPED
[INFO] Yes cart core: Import/Export ....................... SKIPPED
[INFO] Yes cart core: Core jobs ........................... SKIPPED
[INFO] Yes cart core: cart support ........................ SKIPPED
[INFO] Yes cart core: cart support for web ................ SKIPPED
[INFO] Yes cart core DTO service .......................... SKIPPED
[INFO] Yes cart themes modules ............................ SKIPPED
[INFO] Yes cart themes: mail templates .................... SKIPPED
[INFO] Yes cart themes: reports templates ................. SKIPPED
[INFO] Yes cart themes: imagevault structure .............. SKIPPED
[INFO] Yes cart web modules ............................... SKIPPED
[INFO] Yes cart web: web support .......................... SKIPPED
[INFO] Yes cart payment: LiqPay ........................... SKIPPED
[INFO] Yes cart payment: CyberSource ...................... SKIPPED
[INFO] Yes cart payment: AuthorizeNet ..................... SKIPPED
[INFO] Yes cart payment: PayPal ........................... SKIPPED
[INFO] Yes cart payment: PostFinance ...................... SKIPPED
[INFO] Yes cart web: Storefront (Wicket) .................. SKIPPED
[INFO] Yes cart web: REST API ............................. SKIPPED
[INFO] Yes cart Admin modules ............................. SKIPPED
[INFO] Yes cart JAM: value objects ........................ SKIPPED
[INFO] Yes cart JAM: services ............................. SKIPPED
[INFO] Yes cart JAM: JS client ............................ SKIPPED
[INFO] Yes cart JAM: server ............................... SKIPPED
[INFO] Yes cart integrations .............................. SKIPPED
[INFO] Yes cart integration: Price rules .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.669 s
[INFO] Finished at: 2019-01-24T00:19:52-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project core: Compilation failure: Compilation failure:
[ERROR] C:\Abed\devops\projects\commerce\yes-cart-yc-3.5.0-ga\core\src\main\java\org\yes\cart\service\locator\impl\JnpInstantiationStrategyImpl.java:[27,16] error: package javax.rmi does not exist
[ERROR] C:\Abed\devops\projects\commerce\yes-cart-yc-3.5.0-ga\core\src\main\java\org\yes\cart\service\locator\impl\JnpInstantiationStrategyImpl.java:[70,27] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

**Comment by abdullahvhdl** [comment]
solved when switched to JDK 1.8

**Comment by inspire-software** [comment]
FYI there is a jira task for upgrade to JDK 11 https://jira.inspire-software.com/jira/browse/YC-950
It is pushed to v4.x since we want to give some time for existing users to upgrade. 

After all JDK 8 LTS is till March 2022 and JDK 11 is till September 2023 as per https://www.oracle.com/technetwork/java/java-se-support-roadmap.html so some people are reluctant to upgrade (just for the sake of extra year and a bit). 

JDK 11 have removed some APIs, which means it will be a forceful upgrade of prod systems. So we are still assessing best way of doing this.  

Regards,
YC Team
