### ISSUE TITLE
Allow cross origin request for API 

### ISSUE THREAD

**Issue by iazarny** [inspire-software/yes-cart#57]
To consume web server response. Without this header browser just  provide "opaque response "
details here 
https://stackoverflow.com/questions/44268722/fetch-request-completes-successfully-but-response-object-empty

public class CorsFilter implements ContainerResponseFilter {
 
    @Override
    public void filter(ContainerRequestContext requestContext, 
      ContainerResponseContext responseContext) throws IOException {
          responseContext.getHeaders().add(
            "Access-Control-Allow-Origin", "*");
          responseContext.getHeaders().add(
            "Access-Control-Allow-Credentials", "true");
          responseContext.getHeaders().add(
           "Access-Control-Allow-Headers",
           "origin, content-type, accept, authorization");
          responseContext.getHeaders().add(
            "Access-Control-Allow-Methods", 
            "GET, POST, PUT, DELETE, OPTIONS, HEAD");
    }
}

**Comment by inspire-software** [comment]
CORS is now enabled and demo APIs allow the following origins: 

- http://localhost:8080
- https://localhost:8080
- http://localhost
- https://localhost
- http://localhost:5555
- https://localhost:5555

**X-SALES-CHANNEL** header should be **localhost**

Example cURL
```
curl -v -X GET "https://demo.yes-cart.org/api/rest/cart" -H "accept: application/xml" -H "X-SALES-CHANNEL: lo https://localhost:5555"
```
