### ISSUE TITLE
API search response returns not expected result

### ISSUE THREAD

**Issue by iazarny** [inspire-software/yes-cart#60]
**Bug**
With request
```
{
  "search": {
    "category": "string",
    .....
    "pageNumber": 0,
    "pageSize": 0, <--------------------  
.....
```
expected empty item list in response.

**Comment by inspire-software** [comment]
This is a feature to prevent DDoS e.g. if someone puts pageSize=10000000 to retrieve full catalog in one request, which will probably crash the server with OOM. 

pageSize is checked against available page sizes and if it is not defined it defaults to first available size and hence returns results for the minimum page size. Clients are expected to "choose" from available size with is provided in the search response.

**Comment by iazarny** [comment]
Make sense to limit with max allowed value , right.  But  was requested 0 , means, that need some info , but not details. Or lets create one more endpoint

**Comment by inspire-software** [comment]
New property has been added to SearchRO.excludeResults
```
{
  "category": "0",
  "includeNavigation": true,
  "excludeResults": true,
  "pageNumber": 0,
  "pageSize": 10,
  "parameters": { },
  "sortDescending": true,
  "sortField": null
}
```
Set it to true as in the example above to exclude results.

**Comment by iazarny** [comment]
Sorry, the expected result was not fully qualified.   The  "totalResults" field must have real qty of the products in category. Now it 0 if "excludeResults": true set. It used to show product list of something other for selected category.

**Comment by inspire-software** [comment]
Total count is now correctly reflected in excludeResults=true mode as well
