### ISSUE TITLE
API Add control types to /customer/summary

### ISSUE THREAD

**Issue by iazarny** [inspire-software/yes-cart#67]
Add control types to  curl -X GET "https://demo.yes-cart.org/api/rest/customer/summary" -H "accept: application/json" -H "yc: e4179ebd-7abe-4c2d-bc24-a08f1eca4709"
similar to 
curl -X GET "https://demo.yes-cart.org/api/rest/auth/register?customerType=B2C" -H "accept: application/json"

To correct build form with customer information

**Comment by inspire-software** [comment]
Viewing a summary is only possible once you are logged in. The customerType is inferred from the currently signed in customer, therefore summary will only have attributes applicable for given customer type.
