### ISSUE TITLE
Unable to save changes in cp app when modifying payment methods for a carrier

### ISSUE THREAD

**Issue by codelano** [inspire-software/yes-cart#75]
**Describe the bug**
Unable to save changes in cp app when modifying payment methods for a carrier

**To Reproduce**
1. Go to cp application 
2. Navigate to Chipping -> Carriers
3. Select any carrier
4. List items of a selected carrier
5. Select carrier SLA item and click edit
6. Navigate to Payment Methods tab
7. Link new payment method

**Current behaviour**
Save button becomes little green, but unable to click it. No ability to save changes

**Expected behaviour**
Save button becomes green and clickable and able to save

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome, MS Edge

**Additional context**
 - YC version: 3.6.3-GA

**Comment by inspire-software** [comment]
If the "save" button is pale green and not vibrant green - this indicates that you have errors on other tabs. Please check all tabs for red field markers and correct the data errors.

**Comment by codelano** [comment]
That worked, thank you. Closing as not a defect
